### ISSUE TITLE
Recovery Plan Triggering 

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/pswalker#17] opened 2017-07-27 01:24 UTC
Recovery plan did not trigger when it should have. Requires investigation

**Comment by ZLLentz** [comment] 2017-07-27 02:10
Working at [https://github.com/ZLLentz/pswalker/tree/recovery](url)

I'm planning to fix a few issues together here:

1. Implementation is messy because I never went back to clean it up.
2. Implementation is unreliable (stated issue above) because it was designed to be able to recover at almost any moment.
3. Implementation is wrong because it assumes an A+ beam drop suspender exists. This is not true, so either the implementation needs to change or such a suspender needs to be created. The design problem here is differentiating between missing the imager and having no beam. If we are missing the imager, we trigger the recovery plan. If we have no beam, we need to wait.

**Comment by ZLLentz** [comment] 2017-08-07 21:15
Closing this issue because it is handled by pull request #31

**Closed by ZLLentz** 2017-08-07 21:15 UTC
Labels: enhancement
